Add first text for snapshot workflow example
sandialabs/spack-manager pull request #162
Opened 2022-02-09 20:24 UTC by jrood-nrel

2022-02-09 20:35 UTC, jrood-nrel commented
https://jrood-nrel.github.io/spack-manager has this pushed already so you can see the sphinx rendering.

2022-02-09 22:12 UTC, psakievich reviewed
Great progress. Added some thoughts

2022-02-09 22:12 UTC, psakievich commented on docs/snapshot_workflow.md
> +Activating Spack-Manager...
For this section I'd prefer to show people to source the `useful_bash_functions.sh` and have them use `spack-start` instead.  I think that is the model we want to consistently show since that will also enable the `quick-*` commands as well.  

I'd really like for everyone to activate spack-manager that way since it enables the reduced syntax commands.  What are your thoughts?

2022-02-09 22:12 UTC, psakievich commented on docs/snapshot_workflow.md
> +```
here we could add 
```
Both of these steps can be combined into 1 with `quick-create-env -n exawind -s "nalu-wind@master+hypre+cuda cuda_arch=70%gcc"`
```

2022-02-09 22:12 UTC, psakievich commented on docs/snapshot_workflow.md
> +`gcc-cuda`, etc. We also need to "blacklist" any packages we plan on developing locally. Even without building source locally in
If we add develop specs first and then call external it will auto black-list them for us.  It would be good to add that into the documentation here too.

2022-02-09 22:12 UTC, psakievich commented on docs/snapshot_workflow.md
> +==> Warning: the original concretizer is currently being used.
we should add a comment about this warning in the documentation explaining what it is

2022-02-09 22:12 UTC, psakievich commented on docs/snapshot_workflow.md
> +==> Warning: the original concretizer is currently being used.
Also users don't _have_ to concretize here anymore since `spack install` does it. It might be worth taking this section out and having a section on when to reconcretize with the `-f` flag?

2022-02-09 22:20 UTC, jrood-nrel commented on docs/snapshot_workflow.md
> +Activating Spack-Manager...
Sure, I can do that.

2022-02-09 22:21 UTC, jrood-nrel commented on docs/snapshot_workflow.md
> +`gcc-cuda`, etc. We also need to "blacklist" any packages we plan on developing locally. Even without building source locally in
Sure

2022-02-09 22:37 UTC, jrood-nrel commented on docs/snapshot_workflow.md
> +Activating Spack-Manager...
Should that be the `start.sh` then? `useful_bash_functions.sh` is pretty long and doesn't indicate the entry point.

2022-02-09 23:52 UTC, psakievich commented on docs/snapshot_workflow.md
> +Activating Spack-Manager...
hmm good point

2022-02-09 23:52 UTC, jrood-nrel commented on docs/snapshot_workflow.md
> +==> Warning: the original concretizer is currently being used.
I kind of think concretization should be an explicit step because it's a main idea within Spack.

2022-02-09 23:52 UTC, psakievich commented on docs/snapshot_workflow.md
> +Activating Spack-Manager...
The reason for keeping them separate is so people don't have to load spack into their shell until they want it

2022-02-09 23:54 UTC, jrood-nrel commented on docs/snapshot_workflow.md
> +Activating Spack-Manager...
Is there a case where you would want spack-manager activated and not the spack within it? I can't say that is something I would ever do.

2022-02-10 01:51 UTC, psakievich commented on docs/snapshot_workflow.md
> +Activating Spack-Manager...
Well spack-manager isn't activated. Just the scripts to activate it when you want are defined in your shell. To do that you just have SPACK_MANAGER defined and the bash scripts sourced. Then when you call any of the quick-commands it activates spack and spack-manager as part of the process. The idea is minimally invasive additions to the shell to make it activatable at any point.

2022-02-10 15:18 UTC, jrood-nrel commented on docs/snapshot_workflow.md
> +Activating Spack-Manager...
That's fair, but I think everything should go into `start.sh` then like I've done here. I don't think useful_bash_functions should be an entry point.

2022-02-10 15:40 UTC, psakievich requested changes
I like the idea of including `useful_bash_functions.sh` into `start.sh` but I think this change loses the intent behind the `quick-*` commands. See my comment in #170

2022-02-10 15:40 UTC, psakievich commented on start.sh
> +# function to quickly activate an environment
why not just `source ${SPACK_MANAGER}/scripts/useful_bash_functions.sh`?

2022-02-10 15:47 UTC, jrood-nrel commented on start.sh
> +# function to quickly activate an environment
Because if `useful_bash_functions` is the intended entry point, I really think entry should begin in `start.sh`. We can move the `spack-start` to a file in `scripts` if it matters.

2022-02-10 16:39 UTC, psakievich commented on start.sh
> +# function to quickly activate an environment
yeah this fine. I'm on board

2022-02-10 16:47 UTC, psakievich commented on start.sh
> +  source ${SPACK_ROOT}/share/spack/setup-env.sh
```suggestion
if [ -z ${SPACK_MANAGER_MACHINE} ]; then
  export PYTHONPATH=${PYTHONPATH}:${SPACK_MANAGER}/scripts:${SPACK_MANAGER}/spack-scripting/scripting/cmd:${SPACK_MANAGER}/spack-scripting/scripting
  source ${SPACK_ROOT}/share/spack/setup-env.sh
 fi
```

Maybe something like this to make `spack-start` a no-op if it has already been called?

2022-02-10 16:47 UTC, psakievich commented on start.sh
> +function spack-start() {
```suggestion
function spack-manager-start() {
```

2022-02-10 16:50 UTC, jrood-nrel commented on start.sh
> +function spack-start() {
So I was going to make this change, but I think I would decide against it now. I think we should consider `source start.sh` as having spack-manager activated, but `spack-start` as having activated spack. It's also shorter.

2022-02-10 20:37 UTC, psakievich commented on start.sh
> +function spack-start() {
okay that sounds good to me

2022-02-10 20:41 UTC, psakievich approved these changes
LGTM. Let's make a post about this on slack to let the user base know, and add the `remove-spack-prompt` function added in #169. I'll post on slack

2022-02-10 21:59 UTC, psakievich commented
closes #163

2022-02-10 22:16 UTC, merged