Use portable identifiers for bash functions
sandialabs/spack-manager pull request #322
Opened 2022-07-25 21:05 UTC by jrood-nrel

2022-07-26 19:54 UTC, psakievich commented
Any luck on the aliases so we don't have to break backwards compatibility? If not then we should make an announcement about this and give people a little warning before merging.

2022-07-26 21:08 UTC, tasmith4 approved these changes
Love it.  I will need a heads-up though, so that I can update halley to match this.  It would be ideal if there could be a deprecation cycle where both hyphen and underscore versions work side-by-side for a week or two.

2022-07-26 21:22 UTC, jrood-nrel commented
The aliases seem to work.

2022-07-26 21:25 UTC, tasmith4 approved these changes

2022-07-27 13:14 UTC, psakievich approved these changes

2022-07-27 15:00 UTC, psakievich commented
@tasmith4 why don't you pull the trigger on merging this when you are ready?  Also please post a notice in the spack-manager slack channel to give a heads up to people.

2022-07-27 18:09 UTC, tasmith4 commented
@psakievich sure.  what deprecation timeframe do you want to announce for the hyphenated aliases?

2022-07-27 18:13 UTC, jrood-nrel commented
I say we keep the hyphen aliases.

2022-07-27 18:55 UTC, psakievich commented
If we want to keep the hyphens long term then I think we should append all the shell functions with `_` i.e. `_cd_sm` so there aren't two instances that pop up on tab completion. That should make the transition unnoticeable to the user base. Thoughts? I like the idea of keeping  them around too. I'd really not change my command line usage of the hyphened commands.

2022-07-27 19:41 UTC, tasmith4 requested changes
while testing halley I noticed a typo in the doc changes for this -- some of the docs have changed `spack manager create-env` to spack manager create_env`.  I think this is incorrect because the actual python files didn't change, and I also think we don't want to change the hyphens to underscores in the python functions because spack uses hyphens (e.g. `spack build-env`) and I think we should be consistent.

2022-07-27 19:43 UTC, tasmith4 commented
Besides the create-env thing, halley turns out to not depend on any of the hyphenated shell convenience functions, so I no longer care when this goes in if it only applies to shell functions and not python functions.

2022-07-27 20:03 UTC, tasmith4 requested changes
found a few more typos in the docs.  I think this is it

2022-07-27 20:03 UTC, tasmith4 commented on docs/user_profiles/developers/developer_workflow.md
> ++ spack manager create_dev_env -s exawind@master amr-wind@main nalu-wind@master
probable typo

2022-07-27 20:03 UTC, tasmith4 commented on docs/user_profiles/developers/developer_workflow.md
> +usage: spack manager create_dev_env [-h] [-m MACHINE] [-d DIRECTORY | -n NAME] [-y YAML] [-s SPEC [SPEC ...]]
probable typos

2022-07-27 20:03 UTC, tasmith4 commented on start.sh
> +# same as quick_create but calls create_env_dev instead
probable typo carried through from original:  should be `create-dev-env` as per lines 103/107

2022-07-27 20:25 UTC, tasmith4 approved these changes

2022-07-28 00:23 UTC, psakievich commented
> If we want to keep the hyphens long term then I think we should append all the shell functions with `_` i.e. `_cd_sm` so there aren't two instances that pop up on tab completion. That should make the transition unnoticeable to the user base. Thoughts? I like the idea of keeping them around too. I'd rather not change my command line usage of the hyphened commands.

I think we should do this unless you guys are actively opposed to it. This would also make it so we don't need to change the documentation at all.

2022-07-28 02:58 UTC, jrood-nrel commented
Hmm, the aliases seemed to work on my laptop, but they're not working here as I expect.

2022-07-28 03:00 UTC, jrood-nrel commented
Looks like hyphens may not be portable in aliases either.

2022-07-29 21:59 UTC, psakievich commented
Closing based on our discussions.

2022-07-29 21:59 UTC, closed without merging