add sm-clean to the nightly testing
sandialabs/spack-manager pull request #327
Opened 2022-08-11 20:04 UTC by tasmith4

2022-08-11 20:17 UTC, jrood-nrel commented
Ii don't think you want to update Spack here.

2022-08-11 20:18 UTC, jrood-nrel commented on scripts/run-exawind-nightly-tests.sh
> -cmd "spack clean -s || true"
Can the `sm-clean` stay here?

2022-08-11 21:01 UTC, tasmith4 commented on scripts/run-exawind-nightly-tests.sh
> -cmd "spack clean -s || true"
I'm open to suggestions on where to move it, but I think it has to come before the concretize (since the error we saw the other night, that was fixed by sm-clean, happened at concretization)

2022-08-11 22:07 UTC, psakievich commented on scripts/run-exawind-nightly-tests.sh
> -cmd "spack clean -s || true"
It's probably best to have it as early as possible. Definitely before concretization.

2022-08-12 03:12 UTC, jrood-nrel commented on scripts/run-exawind-nightly-tests.sh
> -cmd "spack clean -s || true"
I thought STK wanted the stage directory to persist after the tests ran.

2022-08-12 03:13 UTC, jrood-nrel commented on scripts/run-exawind-nightly-tests.sh
> -cmd "spack clean -s || true"
Oh I'm all screwed up. I think this makes sense.

2022-08-12 03:14 UTC, jrood-nrel requested changes, later dismissed
I'll approve this when the spack submodule is reverted.

2022-08-12 12:36 UTC, tasmith4 commented
yeah @jrood-nrel you're absolutely right, sorry I missed that comment at first, no idea how the spack submodule change got into here.  also confused why the github autolabeler didn't tag it with "update-spack" ...

2022-08-12 15:33 UTC, psakievich approved these changes

2022-08-12 15:34 UTC, merged