promote Trilinos develop to stable
sandialabs/spack-manager pull request #382
Opened 2022-10-28 15:10 UTC by tasmith4

@psakievich @jrood-nrel @PaulMullowney ... seems like from the slack discussion we should go ahead with this.  Let me know if you disagree or think we need to test anything else first.

2022-10-28 15:30 UTC, PaulMullowney commented
I think we should definitely do this. We're gonna have some failing Trilinos tests on multiple devices but hopefully this will encourage people to fix. 

One thing to note, we no longer need to patch trilinos with this promotion.

2022-10-28 15:34 UTC, psakievich commented
So I'm for this, but I'm not sure I want to keep pushing `stable`.  The issue is if I install a new build and it is using `trilinos@stable` it's not clear if it is current.  I'm wondering if we should pursue a versioning strategy like Alegra, use `git.[hash]=stable` in the `packages.yaml` or something along those lines so we have clearer definitions between builds.

2022-10-28 16:19 UTC, tasmith4 commented
I don't have an opinion on pushing `stable` vs a git hash versioning scheme, I'm happy to go with whatever you all like best.  @psakievich or anyone else, if you want to edit this PR to implement a versioning scheme, please feel free.

2022-10-31 13:53 UTC, psakievich commented
I'll put up a pr on a versioning scheme today. I'm thinking just the date `2022.10.24` or something. We'll need to update the nalu-wind core package too.

2022-10-31 15:04 UTC, psakievich requested changes

2022-10-31 15:04 UTC, psakievich commented on repos/exawind/packages/trilinos/package.py
> +    version('stable', commit='da54d929ea62e78ba8e19c7d5aa83dc1e1f767c1')
```suggestion
    version('13.4.0.2022.10.27', commit='da54d929ea62e78ba8e19c7d5aa83dc1e1f767c1')
    version('13.2.0.2022.06.05', commit='7498bcb9b0392c830b83787f3fb0c17079431f06')
```

2022-10-31 15:04 UTC, psakievich commented on repos/exawind/packages/trilinos/package.py
> +    version('stable', commit='da54d929ea62e78ba8e19c7d5aa83dc1e1f767c1')
I'd like to move to actual versions so we maintain a set of commit histories in the package. I realize this may break things. Debate is welcome

2022-10-31 16:04 UTC, psakievich commented on repos/exawind/packages/trilinos/package.py
> +    version('stable', commit='da54d929ea62e78ba8e19c7d5aa83dc1e1f767c1')
I'll open a separate PR for this

2022-11-01 15:57 UTC, tasmith4 commented
closing since #387 supersedes and is merged

2022-11-01 15:57 UTC, closed without merging